PFCDTourismBundle_back:
    resource: "@PFCDTourismBundle/Resources/config/routing/back.yml"
    prefix:   /admin
    
PFCDTourismBundle_front:
    resource: "@PFCDTourismBundle/Resources/config/routing/front.yml"
    prefix:   /