parameters:
#    pfcd_tourism.example.class: PFCD\TourismBundle\Example

services:
    # This extension manage to come back to the previous route after change the locale
    twig.localized.route.extension:
        class: PFCD\TourismBundle\Twig\Extension
        tags:
            - { name: twig.extension }
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        arguments: ["@service_container"]
    
    # This twig extension allows to truncate string of text        
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
        
    # This extension allow to add a help icon with hints about form fields
    form.type_extension.help_message:
        class: PFCD\TourismBundle\Form\Extension\HelpMessageTypeExtension
        tags:
            - { name: form.type_extension, alias: field }
        
    # This extension allow to add a language flag to translatable fields
    form.type_extension.translatable:
        class: PFCD\TourismBundle\Form\Extension\TranslatableTypeExtension
        tags:
            - { name: form.type_extension, alias: field }
        
    # This extension allow to automatically translate a country ISO code to a
    # country name for field choice with a subset of countries
    form.type_extension.countrylist:
        class: PFCD\TourismBundle\Form\Extension\CountryListTypeExtension
        tags:
            - { name: form.type_extension, alias: field }
