parameters:
#    pfcd_tourism.example.class: PFCD\TourismBundle\Example

services:
#    pfcd_tourism.example:
#        class: %pfcd_tourism.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
