PFCD\TourismBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        email:
            - Email:    { groups: [Remember, Default] }
        password:
            - NotBlank: { groups: [Reset, Default] }
            
PFCD\TourismBundle\Entity\Organization:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        username:
            - NotBlank: { groups: [Default] }
        email:
            - Email:    { groups: [Default] }
        password:
            - NotBlank: { groups: [Default] }
        name:
            - NotBlank: { groups: [Default] }
        shortDesc:
            - NotBlank: { groups: [Update] }
        file:
            - Image:    { maxSize: 32k }
            
PFCD\TourismBundle\Entity\Activity:
    properties:
        title:
            - NotBlank: { groups: [Default] }
        shortDesc:
            - NotBlank: { groups: [Default] }
        price:
            - Min:      { limit: 0, message: "activity.price.error", groups: [Default] }
        file:
            - Image:    { maxSize: 32k }
            
PFCD\TourismBundle\Entity\Article:
    properties:
        title:
            - NotBlank: { groups: [Default] }
        shortDesc:
            - NotBlank: { groups: [Default] }
        file:
            - Image:    { maxSize: 32k }
            
PFCD\TourismBundle\Entity\Reservation:
    properties:
        persons:
            - Min:      { limit: 1, message: "reservation.persons.error", groups: [Front, Default] }
            
PFCD\TourismBundle\Entity\Image:
    properties:
        file:
            - Image:    { maxSize: 256k }
