security:
  
    encoders:
        entity_admin:
            class: Symfony\Component\Security\Core\User\User
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
        entity_organization:
            class: PFCD\TourismBundle\Entity\Organization
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
        entity_user:
            class: PFCD\TourismBundle\Entity\User
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    providers:
        in_memory:
            users:
                %admin_username%:
                    password: %admin_password%
                    roles: ROLE_ADMIN
        db_organization:
            entity:
                class: PFCD\TourismBundle\Entity\Organization
                property: username
        db_user:
            entity:
                class: PFCD\TourismBundle\Entity\User
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin_secured_area:
            pattern: /admin/.*
            provider: in_memory
            anonymous: true
            form_login:
                check_path: admin_login_check
                login_path: admin_login
            logout:
                path:   admin_logout
                target: admin_index
        organization_secured_area:
            pattern: /back/.*
            provider: db_organization
            anonymous: true
            form_login:
                check_path: back_login_check
                login_path: back_login
                username_parameter: _username
                password_parameter: _password
            logout:
                path:   back_logout
                target: back_index
        user_secured_area:
            pattern: ^/.*
            provider: db_user
            anonymous: true
            form_login:
                check_path: front_login_check
                login_path: front_login
                username_parameter: _email
                password_parameter: _password
                use_referer: true
            logout:
                path:   front_logout
                target: front_index

    access_control:
        admin_login:
            path: /admin/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        admin_area:
            path: /admin/.*
            roles: ROLE_ADMIN
        organization_login:
            path: /back/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        organization_area:
            path: /back/.*
            roles: ROLE_ORGANIZATION
        user_public_area:
            path: /.*
            roles: IS_AUTHENTICATED_ANONYMOUSLY
