security:
  
    encoders:
        entity_admin:
            class: Symfony\Component\Security\Core\User\User
            algorithm: %admin_encoder_algorithm%
            iterations: %admin_encoder_iterations%
            encode_as_base64: false
        entity_organization:
            class: PFCD\TourismBundle\Entity\Organization
            algorithm: %organization_encoder_algorithm%
            iterations: %organization_encoder_iterations%
            encode_as_base64: false
        entity_user:
            class: PFCD\TourismBundle\Entity\User
            algorithm: %user_encoder_algorithm%
            iterations: %user_encoder_iterations%
            encode_as_base64: false

    providers:
        all_users:
            providers: [in_memory, db_organization, db_user]
        back_users:
            providers: [in_memory, db_organization]
        in_memory:
            users:
                %admin_username%:
                    password: %admin_password%
                    roles: ROLE_ADMIN
        db_organization:
            entity:
                class: PFCD\TourismBundle\Entity\Organization
                property: username
        db_user:
            entity:
                class: PFCD\TourismBundle\Entity\User
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
         # Area to create a translation panel (future development)
#        trans_secured_area:
#            pattern: /translation/.*
#            provider: all_users
#            anonymous: true
#            form_login:
#                check_path: translation_login_check
#                login_path: translation_login
#            logout:
#                path:   translation_logout
#                target: translation_index
        back_secured_area:
            pattern: /admin/.*
            provider: back_users
            anonymous: true
            form_login:
                check_path: back_login_check
                login_path: back_login
            logout:
                path:   back_logout
                target: back_index
        front_secured_area:
            pattern: ^/.*
            provider: db_user
            anonymous: true
            form_login:
                check_path: front_login_check
                login_path: front_login
                username_parameter: _email
                use_referer: true
            logout:
                path:   front_logout
                target: front_index

    access_control:
        # Area to create a translation panel (future development)
#        translation_login:
#            path: /translation/login
#            roles: IS_AUTHENTICATED_ANONYMOUSLY
#        translation_area:
#            path: /translation/.*
#            roles: [ROLE_USER, ROLE_ORGANIZATION, ROLE_ADMIN]
        back_reset:
            path: /admin/reset.*
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        back_remember:
            path: /admin/remember
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        back_login:
            path: /admin/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        back_area:
            path: /admin/.*
            roles: [ROLE_ORGANIZATION, ROLE_ADMIN]
        front_public_area:
            path: /.*
            roles: IS_AUTHENTICATED_ANONYMOUSLY
