security:
  
    encoders:
        entity_admin:
            class: Symfony\Component\Security\Core\User\User
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
        entity_organization:
            class: PFCD\TourismBundle\Entity\Organization
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
        entity_user:
            class: PFCD\TourismBundle\Entity\User
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    providers:
        in_memory:
            users:
                %admin_username%:
                    password: %admin_password%
                    roles: ROLE_ADMIN
        db_organization:
            entity:
                class: PFCD\TourismBundle\Entity\Organization
                property: username
        db_user:
            entity:
                class: PFCD\TourismBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin_secured_area:
            pattern: ^/admin/.*
            provider: in_memory
            anonymous: true
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
            logout:
                path:   /admin/logout
                target: /admin/
        organization_secured_area:
            pattern: ^/back/.*
            provider: db_organization
            anonymous: true
            form_login:
                check_path: /back/login_check
                login_path: /back/login
            logout:
                path:   /back/logout
                target: /back/
        user_secured_area:
            pattern: ^/.*
            provider: db_user
            anonymous: true
            form_login:
                check_path: /login_check
                login_path: /
                use_referer: true
            logout:
                path:   /logout
                target: /

    access_control:
        admin_login:
            path: /admin/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        admin_area:
            path: /admin/.*
            roles: ROLE_ADMIN
        organization_login:
            path: /back/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        organization_area:
            path: /back/.*
            roles: ROLE_ORGANIZATION
        user_public_area:
            path: /.*
            roles: IS_AUTHENTICATED_ANONYMOUSLY
