################################################################################
##### LOGIN SECURITY ###########################################################
################################################################################
    
admin_login:
    pattern:  /login
    defaults: { _controller: PFCDTourismBundle:Admin:login }
    
admin_login_check:
    pattern:  /login_check
    options:  { i18n: false }
    
admin_logout:
    pattern:  /logout
    options:  { i18n: false }

################################################################################
##### ADMIN CONTROLLER #########################################################
################################################################################

admin_index:
    pattern:  /
    defaults: { _controller: PFCDTourismBundle:Admin:index }
    requirements: { _method: get }
        
################################################################################
##### USER CONTROLLER ##########################################################
################################################################################

admin_user_index:
    pattern:  /users
    defaults: { _controller: "PFCDTourismBundle:User:adminIndex" }

admin_user_new:
    pattern:  /user/new
    defaults: { _controller: "PFCDTourismBundle:User:adminNew" }

admin_user_create:
    pattern:  /user/create
    defaults: { _controller: "PFCDTourismBundle:User:adminCreate" }
    requirements: { _method: post }

admin_user_show:
    pattern:  /user/{id}
    defaults: { _controller: "PFCDTourismBundle:User:adminShow" }
    requirements: { id: \d+ }

admin_user_edit:
    pattern:  /user/{id}/edit
    defaults: { _controller: "PFCDTourismBundle:User:adminEdit" }
    requirements: { id: \d+ }

admin_user_update:
    pattern:  /user/{id}/update
    defaults: { _controller: "PFCDTourismBundle:User:adminUpdate" }
    requirements: { _method: post, id: \d+ }

admin_user_delete:
    pattern:  /user/{id}/delete
    defaults: { _controller: "PFCDTourismBundle:User:adminDelete" }
    requirements: { _method: post, id: \d+ }
    
################################################################################
##### ORGANIZATION CONTROLLER ##################################################
################################################################################

admin_organization_index:
    pattern:  /organizations
    defaults: { _controller: "PFCDTourismBundle:Organization:adminIndex" }

admin_organization_new:
    pattern:  /organization/new
    defaults: { _controller: "PFCDTourismBundle:Organization:adminNew" }

admin_organization_create:
    pattern:  /organization/create
    defaults: { _controller: "PFCDTourismBundle:Organization:adminCreate" }
    requirements: { _method: post }

admin_organization_show:
    pattern:  /organization/{id}
    defaults: { _controller: "PFCDTourismBundle:Organization:adminShow" }
    requirements: { id: \d+ }

admin_organization_edit:
    pattern:  /organization/{id}/edit
    defaults: { _controller: "PFCDTourismBundle:Organization:adminEdit" }
    requirements: { id: \d+ }

admin_organization_update:
    pattern:  /organization/{id}/update
    defaults: { _controller: "PFCDTourismBundle:Organization:adminUpdate" }
    requirements: { _method: post, id: \d+ }

admin_organization_delete:
    pattern:  /organization/{id}/delete
    defaults: { _controller: "PFCDTourismBundle:Organization:adminDelete" }
    requirements: { _method: post, id: \d+ }

################################################################################
##### ACTIVITY CONTROLLER ######################################################
################################################################################
    
admin_activity_index:
    pattern:  /activities
    defaults: { _controller: "PFCDTourismBundle:Activity:adminIndex" }

admin_activity_show:
    pattern:  /activity/{id}/show
    defaults: { _controller: "PFCDTourismBundle:Activity:adminShow" }
    requirements: { id: \d+ }

admin_activity_new:
    pattern:  /activity/new
    defaults: { _controller: "PFCDTourismBundle:Activity:adminNew" }

admin_activity_create:
    pattern:  /activity/create
    defaults: { _controller: "PFCDTourismBundle:Activity:adminCreate" }
    requirements: { _method: post }

admin_activity_edit:
    pattern:  /activity/{id}/edit
    defaults: { _controller: "PFCDTourismBundle:Activity:adminEdit" }
    requirements: { id: \d+ }

admin_activity_update:
    pattern:  /activity/{id}/update
    defaults: { _controller: "PFCDTourismBundle:Activity:adminUpdate" }
    requirements: { _method: post, id: \d+ }

admin_activity_delete:
    pattern:  /activity/{id}/delete
    defaults: { _controller: "PFCDTourismBundle:Activity:adminDelete" }
    requirements: { _method: post, id: \d+ }