################################################################################
##### LOGIN SECURITY ###########################################################
################################################################################
    
back_login:
    pattern:  /login
    defaults: { _controller: PFCDTourismBundle:Back:login }
    requirements: { _method: get }
    
back_login_check:
    pattern:  /login_check
    options:  { i18n: false }
    requirements: { _method: post }
    
back_logout:
    pattern:  /logout
    options:  { i18n: false }
    requirements: { _method: get }


################################################################################
##### BACK CONTROLLER ##########################################################
################################################################################

back_index:
    pattern:  /
    defaults: { _controller: PFCDTourismBundle:Back:index }
    requirements: { _method: get }


################################################################################
##### USER CONTROLLER ##########################################################
################################################################################

back_user_index:
    pattern:  /users
    defaults: { _controller: "PFCDTourismBundle:User:backIndex" }
    requirements: { _method: get }

back_user_create:
    pattern:  /user/new
    defaults: { _controller: "PFCDTourismBundle:User:backCreate" }

back_user_read:
    pattern:  /user/{id}
    defaults: { _controller: "PFCDTourismBundle:User:backRead" }
    requirements: { _method: get, id: \d+ }

back_user_update:
    pattern:  /user/{id}/edit
    defaults: { _controller: "PFCDTourismBundle:User:backUpdate" }
    requirements: { id: \d+ }

back_user_delete:
    pattern:  /user/{id}/delete
    defaults: { _controller: "PFCDTourismBundle:User:backDelete" }
    requirements: { _method: post, id: \d+ }


################################################################################
##### ORGANIZATION CONTROLLER ##################################################
################################################################################

back_organization_index:
    pattern:  /organizations
    defaults: { _controller: "PFCDTourismBundle:Organization:backIndex" }
    requirements: { _method: get }

back_organization_create:
    pattern:  /organization/new
    defaults: { _controller: "PFCDTourismBundle:Organization:backCreate" }
    
back_organization_read:
    pattern:  /organization/{id}
    defaults: { _controller: "PFCDTourismBundle:Organization:backRead" }
    requirements: { _method: get, id: \d+ }
    
back_organization_preview:
    pattern:  /organization/{id}/preview
    defaults: { _controller: "PFCDTourismBundle:Organization:backPreview" }
    requirements: { _method: get, id: \d+ }

back_organization_update:
    pattern:  /organization/{id}/edit
    defaults: { _controller: "PFCDTourismBundle:Organization:backUpdate" }
    requirements: { id: \d+ }

back_organization_media:
    pattern:  /organization/{id}/media
    defaults: { _controller: "PFCDTourismBundle:Organization:backMedia" }
    requirements: { id: \d+ }

back_organization_delete:
    pattern:  /organization/{id}/delete
    defaults: { _controller: "PFCDTourismBundle:Organization:backDelete" }
    requirements: { _method: post, id: \d+ }


################################################################################
##### ACTIVITY CONTROLLER ######################################################
################################################################################
    
back_activity_index:
    pattern:  /activities
    defaults: { _controller: "PFCDTourismBundle:Activity:backIndex" }
    requirements: { _method: get }

back_activity_create:
    pattern:  /activity/new
    defaults: { _controller: "PFCDTourismBundle:Activity:backCreate" }

back_activity_read:
    pattern:  /activity/{id}
    defaults: { _controller: "PFCDTourismBundle:Activity:backRead" }
    requirements: { _method: get, id: \d+ }

back_activity_preview:
    pattern:  /activity/{id}/preview
    defaults: { _controller: "PFCDTourismBundle:Activity:backPreview" }
    requirements: { _method: get, id: \d+ }

back_activity_calendar:
    pattern:  /activity/calendar
    defaults: { _controller: "PFCDTourismBundle:Activity:calendar" }
    requirements: { _method: get }

back_activity_update:
    pattern:  /activity/{id}/edit
    defaults: { _controller: "PFCDTourismBundle:Activity:backUpdate" }
    requirements: { id: \d+ }

back_activity_media:
    pattern:  /activity/{id}/media
    defaults: { _controller: "PFCDTourismBundle:Activity:backMedia" }
    requirements: { id: \d+ }

back_activity_delete:
    pattern:  /activity/{id}/delete
    defaults: { _controller: "PFCDTourismBundle:Activity:backDelete" }
    requirements: { _method: post, id: \d+ }


################################################################################
##### RESOURCE CONTROLLER ######################################################
################################################################################

back_resource_index:
    pattern:  /resources
    defaults: { _controller: "PFCDTourismBundle:Resource:backIndex" }
    requirements: { _method: get }

back_resource_create:
    pattern:  /resource/new
    defaults: { _controller: "PFCDTourismBundle:Resource:backCreate" }

back_resource_read:
    pattern:  /resource/{id}
    defaults: { _controller: "PFCDTourismBundle:Resource:backRead" }
    requirements: { _method: get, id: \d+ }

back_resource_update:
    pattern:  /resource/{id}/edit
    defaults: { _controller: "PFCDTourismBundle:Resource:backUpdate" }
    requirements: { id: \d+ }

back_resource_delete:
    pattern:  /resource/{id}/delete
    defaults: { _controller: "PFCDTourismBundle:Resource:backDelete" }
    requirements: { _method: post, id: \d+ }


################################################################################
##### SESSION CONTROLLER #######################################################
################################################################################

back_session_index:
    pattern:  /sessions
    defaults: { _controller: "PFCDTourismBundle:Session:backIndex" }

back_session_create:
    pattern:  /session/new
    defaults: { _controller: "PFCDTourismBundle:Session:backCreate" }

back_session_generate:
    pattern:  /session/generate
    defaults: { _controller: "PFCDTourismBundle:Session:backGenerate" }

back_session_read:
    pattern:  /session/{id}
    defaults: { _controller: "PFCDTourismBundle:Session:backRead" }
    requirements: { _method: get, id: \d+ }

back_session_update:
    pattern:  /session/{id}/edit
    defaults: { _controller: "PFCDTourismBundle:Session:backUpdate" }
    requirements: { id: \d+ }

back_session_delete:
    pattern:  /session/{id}/delete
    defaults: { _controller: "PFCDTourismBundle:Session:backDelete" }
    requirements: { _method: post, id: \d+ }


################################################################################
##### RESERVATION CONTROLLER ###################################################
################################################################################

back_reservation_index:
    pattern:  /reservations
    defaults: { _controller: "PFCDTourismBundle:Reservation:backIndex" }

back_reservation_create:
    pattern:  /reservation/new
    defaults: { _controller: "PFCDTourismBundle:Reservation:backCreate" }

back_reservation_read:
    pattern:  /reservation/{id}
    defaults: { _controller: "PFCDTourismBundle:Reservation:backRead" }
    requirements: { _method: get, id: \d+ }

back_reservation_update:
    pattern:  /reservation/{id}/edit
    defaults: { _controller: "PFCDTourismBundle:Reservation:backUpdate" }
    requirements: { id: \d+ }

back_reservation_delete:
    pattern:  /reservation/{id}/delete
    defaults: { _controller: "PFCDTourismBundle:Reservation:backDelete" }
    requirements: { _method: post, id: \d+ }


################################################################################
##### PAYMENT CONTROLLER #######################################################
################################################################################

back_payment_index:
    pattern:  /payments
    defaults: { _controller: "PFCDTourismBundle:Payment:backIndex" }

back_payment_read:
    pattern:  /payment/{id}
    defaults: { _controller: "PFCDTourismBundle:Payment:backRead" }
    requirements: { _method: get, id: \d+ }

back_payment_update:
    pattern:  /payment/{id}/edit
    defaults: { _controller: "PFCDTourismBundle:Payment:backUpdate" }
    requirements: { id: \d+ }
    

################################################################################
##### ARTICLE CONTROLLER ##########################################################
################################################################################
    
back_article_index:
    pattern:  /news
    defaults: { _controller: "PFCDTourismBundle:Article:backIndex" }
    requirements: { _method: get }

back_article_create:
    pattern:  /article/new
    defaults: { _controller: "PFCDTourismBundle:Article:backCreate" }

back_article_read:
    pattern:  /article/{id}
    defaults: { _controller: "PFCDTourismBundle:Article:backRead" }
    requirements: { _method: get, id: \d+ }

back_article_preview:
    pattern:  /article/{id}/preview
    defaults: { _controller: "PFCDTourismBundle:Article:backPreview" }
    requirements: { _method: get, id: \d+ }

back_article_update:
    pattern:  /article/{id}/edit
    defaults: { _controller: "PFCDTourismBundle:Article:backUpdate" }
    requirements: { id: \d+ }

back_article_media:
    pattern:  /article/{id}/media
    defaults: { _controller: "PFCDTourismBundle:Article:backMedia" }
    requirements: { id: \d+ }

back_article_delete:
    pattern:  /article/{id}/delete
    defaults: { _controller: "PFCDTourismBundle:Article:backDelete" }
    requirements: { _method: post, id: \d+ }