################################################################################
##### LOGIN SECURITY ###########################################################
################################################################################
    
front_login:
    pattern:  /login
    defaults: { _controller: PFCDTourismBundle:Front:login }
    requirements: { _method: get }
    
front_login_check:
    pattern:  /login_check
    options:  { i18n: false }
    requirements: { _method: post }
    
front_logout:
    pattern:  /logout
    options:  { i18n: false }
    requirements: { _method: get }
    
front_remember_password:
    pattern:  /remember
    defaults: { _controller: PFCDTourismBundle:Front:rememberPassword }     
    
front_reset_password:
    pattern:  /reset-{id}-key-{key}
    defaults: { _controller: PFCDTourismBundle:Front:resetPassword }        
    
front_activate_user:
    pattern:  /activate-{id}-key-{key}
    defaults: { _controller: PFCDTourismBundle:Front:activateUser }
    requirements: { _method: get }


################################################################################
##### FRONT CONTROLLER #########################################################
################################################################################

front_index:
    pattern:  /
    defaults: { _controller: PFCDTourismBundle:Front:index }
    requirements: { _method: get }
        
front_contact:
    pattern:  /contact
    defaults: { _controller: PFCDTourismBundle:Front:contact }
        
front_about:
    pattern:  /about
    defaults: { _controller: PFCDTourismBundle:Front:about }
    requirements: { _method: get }


################################################################################
##### USER CONTROLLER ##########################################################
################################################################################

front_user_create:
    pattern:  /register
    defaults: { _controller: PFCDTourismBundle:User:frontCreate}

front_user_read:
    pattern:  /user/{id}
    defaults: { _controller: "PFCDTourismBundle:User:frontRead" }
    requirements: { _method: get, id: \d+ }

front_user_update:
    pattern:  /user/edit
    defaults: { _controller: "PFCDTourismBundle:User:frontUpdate" }

front_user_security:
    pattern:  /user/security
    defaults: { _controller: "PFCDTourismBundle:User:frontSecurity" }

front_user_delete:
    pattern:  /user/delete
    defaults: { _controller: "PFCDTourismBundle:User:frontDelete" }
    requirements: { _method: post }


################################################################################
##### ORGANIZATION CONTROLLER ##################################################
################################################################################

front_organization_index:
    pattern:  /organizations
    defaults: { _controller: PFCDTourismBundle:Organization:frontIndex }
    
front_organization_create:
    pattern:  /join
    defaults: { _controller: PFCDTourismBundle:Organization:frontCreate}
    
front_organization_read:
    pattern:  /organization/{id}
    defaults: { _controller: "PFCDTourismBundle:Organization:frontRead" }
    requirements: { _method: get, id: \d+ }
    
front_organization_activities:
    pattern:  /organization/{id}/activities
    defaults: { _controller: "PFCDTourismBundle:Organization:frontActivities" }
    requirements: { _method: get, id: \d+ }
    
front_organization_articles:
    pattern:  /organization/{id}/news
    defaults: { _controller: "PFCDTourismBundle:Organization:frontArticles" }
    requirements: { _method: get, id: \d+ }
    
front_organization_donate:
    pattern:  /organization/{id}/donate
    defaults: { _controller: "PFCDTourismBundle:Organization:frontDonate" }
    requirements: { _method: get, id: \d+ }
    
front_organization_contact:
    pattern:  /organization/{id}/contact
    defaults: { _controller: "PFCDTourismBundle:Organization:frontContact" }
    requirements: { id: \d+ }


################################################################################
##### ACTIVITY CONTROLLER ######################################################
################################################################################
    
front_activity_index:
    pattern:  /activities
    defaults: { _controller: "PFCDTourismBundle:Activity:frontIndex" }

front_activity_read:
    pattern:  /activity/{id}
    defaults: { _controller: "PFCDTourismBundle:Activity:frontRead" }
    requirements: { _method: get, id: \d+ }
    
front_activity_calendar:
    pattern:  /activity/calendar
    defaults: { _controller: "PFCDTourismBundle:Activity:calendar" }
    requirements: { _method: get }


################################################################################
##### RESERVATION CONTROLLER ###################################################
################################################################################

front_reservation_index:
    pattern:  /user/reservations
    defaults: { _controller: "PFCDTourismBundle:Reservation:frontIndex" }
    requirements: { _method: get, id: \d+ }

front_reservation_create:
    pattern:  /activity/{activityId}/booking/{sessionId}
    defaults: { _controller: PFCDTourismBundle:Reservation:frontCreate}
    requirements: { activityId: \d+, sessionId: \d+ }

front_reservation_read:
    pattern:  /user/reservation/{id}
    defaults: { _controller: "PFCDTourismBundle:Reservation:frontRead" }
    requirements: { _method: get, id: \d+ }

front_reservation_delete:
    pattern:  /user/reservation/{id}/delete
    defaults: { _controller: "PFCDTourismBundle:Reservation:frontDelete" }
    requirements: { _method: post, id: \d+ }


################################################################################
##### PAYMENT CONTROLLER #######################################################
################################################################################

front_payment_read:
    pattern:  /user/payment/{id}
    defaults: { _controller: "PFCDTourismBundle:Payment:frontRead" }
    requirements: { _method: get, id: \d+ }

front_payment_update:
    pattern:  /user/payment/{id}/edit
    defaults: { _controller: "PFCDTourismBundle:Payment:frontUpdate" }
    requirements: { id: \d+ }
    

################################################################################
##### ARTICLE CONTROLLER #######################################################
################################################################################
    
front_article_index:
    pattern:  /news
    defaults: { _controller: "PFCDTourismBundle:Article:frontIndex" }

front_article_read:
    pattern:  /article/{id}
    defaults: { _controller: "PFCDTourismBundle:Article:frontRead" }
    requirements: { _method: get, id: \d+ }
    

################################################################################
##### COMMENT CONTROLLER #######################################################
################################################################################

front_comment_activity:
    pattern:  /activity/{id}/comment
    defaults: { _controller: "PFCDTourismBundle:Comment:frontActivity" }
    requirements: { _method: post, id: \d+ }

front_comment_article:
    pattern:  /article/{id}/comment
    defaults: { _controller: "PFCDTourismBundle:Comment:frontArticle" }
    requirements: { _method: post, id: \d+ }