################################################################################
##### LOGIN SECURITY ###########################################################
################################################################################
    
front_login:
    pattern:  /login
    defaults: { _controller: PFCDTourismBundle:Front:login }
    requirements: { _method: get }
    
front_login_check:
    pattern:  /login_check
    options:  { i18n: false }
    requirements: { _method: post }
    
front_logout:
    pattern:  /logout
    options:  { i18n: false }
    requirements: { _method: get }
    
front_remember_password:
    pattern:  /remember
    defaults: { _controller: PFCDTourismBundle:Front:rememberPassword }     
    
front_reset_password:
    pattern:  /reset-{id}-key-{key}
    defaults: { _controller: PFCDTourismBundle:Front:resetPassword }        
    
front_activate_user:
    pattern:  /activate-{id}-key-{key}
    defaults: { _controller: PFCDTourismBundle:Front:activateUser }
    requirements: { _method: get }


################################################################################
##### FRONT CONTROLLER #########################################################
################################################################################

front_index:
    pattern:  /
    defaults: { _controller: PFCDTourismBundle:Front:index }
    requirements: { _method: get }
        
front_contact:
    pattern:  /contact
    defaults: { _controller: PFCDTourismBundle:Front:contact }
        
front_about:
    pattern:  /about
    defaults: { _controller: PFCDTourismBundle:Front:about }
    requirements: { _method: get }


################################################################################
##### USER CONTROLLER ##########################################################
################################################################################

front_user_create:
    pattern:  /register
    defaults: { _controller: PFCDTourismBundle:User:frontCreate}

front_user_read:
    pattern:  /user/{id}
    defaults: { _controller: "PFCDTourismBundle:User:frontRead" }
    requirements: { _method: get, id: \d+ }

front_user_update:
    pattern:  /user/edit
    defaults: { _controller: "PFCDTourismBundle:User:frontUpdate" }

front_user_delete:
    pattern:  /user/delete
    defaults: { _controller: "PFCDTourismBundle:User:frontDelete" }
    requirements: { _method: post }


################################################################################
##### ORGANIZATION CONTROLLER ##################################################
################################################################################

front_organization_index:
    pattern:  /organizations
    defaults: { _controller: PFCDTourismBundle:Organization:frontIndex }
    requirements: { _method: get }
    
front_organization_read:
    pattern:  /organization/{id}
    defaults: { _controller: "PFCDTourismBundle:Organization:frontRead" }
    requirements: { _method: get, id: \d+ }


################################################################################
##### ACTIVITY CONTROLLER ######################################################
################################################################################
    
front_activity_index:
    pattern:  /activities
    defaults: { _controller: "PFCDTourismBundle:Activity:frontIndex" }
    requirements: { _method: get }

front_activity_read:
    pattern:  /activity/{id}
    defaults: { _controller: "PFCDTourismBundle:Activity:frontRead" }
    requirements: { _method: get, id: \d+ }


################################################################################
##### RESERVATION CONTROLLER ###################################################
################################################################################

front_reservation_index:
    pattern:  /user/reservations
    defaults: { _controller: "PFCDTourismBundle:Reservation:frontIndex" }
    requirements: { _method: get, id: \d+ }

front_reservation_create:
    pattern:  /activity/{activityId}/booking
    defaults: { _controller: PFCDTourismBundle:Reservation:frontCreate}
    requirements: { activityId: \d+ }

front_reservation_read:
    pattern:  /user/reservation/{id}
    defaults: { _controller: "PFCDTourismBundle:Reservation:frontRead" }
    requirements: { _method: get, id: \d+ }

front_reservation_update:
    pattern:  /user/reservation/{id}/edit
    defaults: { _controller: "PFCDTourismBundle:Reservation:frontUpdate" }
    requirements: { id: \d+ }

front_reservation_delete:
    pattern:  /user/reservation/{id}/delete
    defaults: { _controller: "PFCDTourismBundle:Reservation:frontDelete" }
    requirements: { _method: post, id: \d+ }